AllCops:
  Exclude:
    - "spec/spec_helper.rb"
  TargetRubyVersion: 3.2

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - "spec/**.rb"

Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**.rb"

Naming/MethodParameterName:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

# a, b = foo1, foo2
Style/ParallelAssignment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
